// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABkf6NshXfTw1eyRMEHii8C9embhYAVvQ',
    appId: '1:497984472938:web:e7d39bfe24684bd3a24713',
    messagingSenderId: '497984472938',
    projectId: 'ebisu-b8894',
    authDomain: 'ebisu-b8894.firebaseapp.com',
    storageBucket: 'ebisu-b8894.firebasestorage.app',
    measurementId: 'G-CLXNNJ0N16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhcZbMvTEjrrPH4rPaMm2aSmbkRvM5r3U',
    appId: '1:497984472938:android:826b9ba4c02a12a7a24713',
    messagingSenderId: '497984472938',
    projectId: 'ebisu-b8894',
    storageBucket: 'ebisu-b8894.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ98yw0Q22eOLqFIfS4StIX5-zqehDs9I',
    appId: '1:497984472938:ios:cb1922f2e9d3f925a24713',
    messagingSenderId: '497984472938',
    projectId: 'ebisu-b8894',
    storageBucket: 'ebisu-b8894.firebasestorage.app',
    iosBundleId: 'com.example.crypto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ98yw0Q22eOLqFIfS4StIX5-zqehDs9I',
    appId: '1:497984472938:ios:cb1922f2e9d3f925a24713',
    messagingSenderId: '497984472938',
    projectId: 'ebisu-b8894',
    storageBucket: 'ebisu-b8894.firebasestorage.app',
    iosBundleId: 'com.example.crypto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABkf6NshXfTw1eyRMEHii8C9embhYAVvQ',
    appId: '1:497984472938:web:7f7e5934ff54a77fa24713',
    messagingSenderId: '497984472938',
    projectId: 'ebisu-b8894',
    authDomain: 'ebisu-b8894.firebaseapp.com',
    storageBucket: 'ebisu-b8894.firebasestorage.app',
    measurementId: 'G-GZ0XXY4FS8',
  );

}